### ISSUE TITLE
Cannot access AppVeyor Project

### ISSUE THREAD

**Issue by Felixmil** [Open-Systems-Pharmacology/OSPSuite-R#1384] opened 2024-04-02 09:06 UTC
Usually, we get PKSim minimal from this link: <https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-r/artifacts/pksim_minimal.zip>

But for some reason, this is not accessible anymore.

Also, I cannot access to the AppVeyor build page. For instance: https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-r-81na1/builds/49469302 returns:

![image](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/assets/34234913/df51c8e1-8c35-4bdb-995a-558204808b55)

**Comment by Yuri05** [comment] 2024-04-02 12:08
https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-r/artifacts/pksim_minimal.zip

> Usually, we get PKSim minimal from this link: https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-r/artifacts/pksim_minimal.zip
> 
> But for some reason, this is not accessible anymore.

This is because the version was temporarily downgraded from 12.0 to 11.3 for the upcoming 11.3 release of the suite.
After 11.3 was released (in the next days) and the version was reverted to 12.0 - should work again.
Seems that we need a better procedure for the hotfixes in the future...



> Also, I cannot access to the AppVeyor build page. For instance: https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-r-81na1/builds/49469302 returns:

Cannot access it as well. What is `ospsuite-r-81na1` ?

**Comment by Yuri05** [comment] 2024-04-10 20:50
The problem is fixed now (PK-Sim was switched back to the 12-build).
However, the nightly build still fails due to some errors in vignettes

```
[197s] ERROR
Errors in running code in vignettes:
when running code in 'set-values.Rmd'
  ...
   Path: Organism|StateVariable_Parameter 
   Value: 10.00 
   isConstant: TRUE 
   isStateVariable: FALSE 
> stateVariableParam$isStateVariable <- TRUE
  When sourcing 'set-values.R':
Error: Creating a RHS Formula is not supported at the moment. This should be done in MoBi.
Execution halted
when running code in 'table-parameters.Rmd'
  ...
  When sourcing 'table-parameters.R':
Error: Type:    OSPSuite.Core.Domain.ValuePointAlreadyExistsForPointException
Message: A point for x=0 was already added with y=1
Method:  Int32 AddPoint(OSPSuite.Core.Domain.Formulas.ValuePoint)
Stack trace:
   at OSPSuite.Core.Domain.Formulas.TableFormula.AddPoint(ValuePoint point)
   at OSPSuite.Core.Domain.Formulas.TableFormula.AddPoint(Double x, Double y)
Execution halted
when running code in 'unit-conversion.Rmd'
  ...
  When sourcing 'unit-conversion.R':
Error: Type:    OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Unit 'kg/m²' is not defined in dimension 'BMI'.
Method:  Double[] convertToBaseUnit(OSPSuite.Core.Domain.UnitSystem.IDimension, System.String, System.Nullable`1[System.Double], Double[])
Stack trace:
   at OSPSuite.R.Services.DimensionTask.convertToBaseUnit(IDimension dimension, String displayUnit, Nullable`1 molWeight, Double[] valuesInDisplayUnit)
   at OSPSuite.R.Services.DimensionTask.ConvertToBaseUnit(String dimensionName, String displayUnit, Double valueInDisplayUnit)
```

**Closed** 2024-04-11 12:29 UTC
