### ISSUE TITLE
DataCombined Transformations (Y-ScaleFactor): adjust arithmetic error scaling

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#1131] opened 2022-09-19 11:39 UTC
But this is in fact an error in the formula: for the arithmetic error it should be then 
`newErrorValue = rawErrorValue * abs(yScaleFactor)`

With this correction I think we can allow negative scale factors indeed

**Comment by PavelBal** [comment] 2022-09-19 12:59
Duplicate of https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1130

**Closed by PavelBal** 2022-09-19 12:59 UTC
Labels: type: bug
