### ISSUE TITLE
Function: create_individual

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#72] opened 2019-07-24 15:05 UTC
## Input:
- Species
- Population
- Gender
- Age
- Weight
- Height
- BMI
- Gestational_age

## Output:
- A list of parameter `path <-> value` tuples that is sufficient to describe a given individual.
- Minimal set
- Parameters defined by formulas should be only returned if necessary
- Option to export to csv in a format that can be loaded in MoBi

**Comment by msevestre** [comment] 2019-07-24 15:10
I'd like to ensure that we use an object for the input instead of lots of single parameters. We have the object already so that we can reuse

**Comment by Yuri05** [comment] 2019-07-24 15:23
>Input:

    Species
    Population
    Gender
    Age
    Weight
    Height
    BMI
    Gestational_age

Enzyme-Ontogenies?
@KatrinCoboeken FYI

**Comment by Yuri05** [comment] 2019-07-24 15:28
like in CreatePopulation(https://github.com/Open-Systems-Pharmacology/2R/issues/40) it would be good to have units as part of the input as well

**Comment by Yuri05** [comment] 2019-07-24 15:28
what will happen if all 3 inputs weight/height/BMI are filled?

**Comment by Yuri05** [comment] 2019-07-24 15:29
>* Minimal set

What does it mean?

>* Parameters defined by formulas should be only returned if necessary

What does it mean?

**Comment by PavelBal** [comment] 2019-07-24 17:11
> like in CreatePopulation(#40) it would be good to have units as part of the input as well

Hm, why? Or should we make this possible for **all** input/output functions?

> what will happen if all 3 inputs weight/height/BMI are filled?

For example, calculate BMI from the given weight and height. If the calculated value deviates from the given for a value higher than a threshold, either a warning or an error is produced (I prefer error).

> What does it mean?
E.g. now the parameters "Specific blood flow rate" and "Blood flow rate" are returned for all organs. Obviously (or not?), "Blood flow rate" is not necessary as it is defined by a formula utilizing the "Specific blood flow rate".

**Comment by Yuri05** [comment] 2019-07-24 17:30
> Hm, why? Or should we make this possible for all input/output functions?

Maybe indeed for all. But CreateIndovidual/Population is something pretty special, so here I would like to have units for sure.

> For example, calculate BMI from the given weight and height. If the calculated value deviates from the given for a value higher than a threshold, either a warning or an error is produced (I prefer error).

Like in the current Matlab toolbox. Never liked this behaviour

> E.g. now the parameters "Specific blood flow rate" and "Blood flow rate" are returned for all organs.
Obviously (or not?), "Blood flow rate" is not necessary as it is defined by a formula utilizing the "Specific blood flow rate".

OK

**Comment by PavelBal** [comment] 2019-07-24 18:08
> Like in the current Matlab toolbox. Never liked this behaviour

:D Ok, what would you prefer?

**Comment by KatrinCoboeken** [comment] 2019-07-25 06:31
It would be very helpful to get also ontogeny factors in the Output. That means the Input must contain a list of the relevant enzymes.

**Comment by msevestre** [comment] 2019-12-04 16:31
@PavelBal Will work on adding PKSim.R to PKSim install
PKSim path will hvae to be read fromregistry based on current verison (e.g. v9 for v9 of OSPSuite.R) or specified as path for portable version

Won't be supported on linux for now

You can start defining the skeleton anytime

**Comment by msevestre** [comment] 2019-12-12 22:18
@PavelBal ok no feedback here, unfortunately. 

However I have started the implementation and I am hitting a serious wall
```
Failed to resolve an implementation of IIndividualFactory
-----------------------------------------------------
The requested service 'PKSim.R.Services.IIndividualFactory' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
Error in rClr::clrCallStatic("PKSim.R.Api", "GetIndividualFactory") : 
  Type:    Autofac.Core.Registration.ComponentNotRegisteredException
Message: The requested service 'PKSim.R.Services.IIndividualFactory' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
Method:  System.Object ResolveService(Autofac.IComponentContext, Autofac.Core.Service, System.Collections.Generic.IEnumerable`1[Autofac.Core.Parameter])
Stack trace:
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at OSPSuite.Infrastructure.Container.Autofac.AutofacContainer.Resolve[TInterface]()
   at OSPSuite.Utility.Container.IoC.Resolve[TImplementationOfInterface]()
```

What's happening is that rClr gets all confused because I am loading OSPSuite.Core and PKSim.R 
somehow stuff gets mixed within each other. I can tell because the instance of the Container in PKSim is NOT Autofac. But calling a PKSim function is being resolved in Autofac

Long story short, it might not be as simple as expected...

**Comment by msevestre** [comment] 2019-12-13 13:40
@PavelBal @Yuri05 Spent a lot of time last night trying to find a solution and I may have something...
Also hoffnung nicht aufgeben

**Comment by PavelBal** [comment] 2019-12-13 14:53
@msevestre It is definitely possible using the current Matlab-implementation of `PKSimCreateIndividual`, see here:
https://github.com/PavelBal/rDotNet_feasibility/blob/master/PKSimCreateIndividual.R

**Comment by msevestre** [comment] 2019-12-13 15:03
Yeah but it's not using rclr. The issue is that ospsuite.core is loaded twice (one from Pksim and one from the ospsuite.r.dll) and it all goes to shit

**Comment by PavelBal** [comment] 2019-12-13 15:17
What do you mean "not using rClr"? The script I linked here uses rClr:

```
loadPKSimMatlabDLL = function(){
  PKSimDir = getPathToPKSimInstallDir();
  clrLoadAssembly(paste0(PKSimDir, "/PKSim.Matlab.dll"));
  clrLoadAssembly(paste0(PKSimDir, "/PKSim.Core.dll"));
}
```

**Comment by msevestre** [comment] 2019-12-13 15:45
oh I see. Well at any rate, this does not work because we are loading two difference instances of OSPSuite.Core, both of them creating a container etc.. 
anyways, hope to get something working soin

**Comment by msevestre** [comment] 2019-12-13 15:48
but this is useful to see this function. Can probably reuse some of it

**Closed** 2020-01-10 16:43 UTC
Labels: type: task
