### ISSUE TITLE
`plotIndividualTimeProfile'  - legend symbols should correspond to plotted symbols

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1187] opened 2023-01-23 13:17 UTC
When mutliple data set are in one DataCombined and are not grouped, they all get the same symbol in the legend:

![image](https://user-images.githubusercontent.com/25903040/214049137-03fafb3f-871f-4cdd-8f6b-b8f9ef60077c.png)

**Comment by Felixmil** [comment] 2023-03-10 14:06
Duplicate of #1206

**Closed by Felixmil** 2023-03-10 14:06 UTC
Labels: type: bug
